#!/bin/bash
# FinFlag · Environment Setup Script (Mac / Linux / WSL)
# Run this ONCE from the project root:  bash setup_env.sh
# ------------------------------------------------------------------

echo ""
echo "================================================"
echo "  FinFlag · Environment Setup"
echo "================================================"
echo ""

# ── 1. Check Python version ─────────────────────────────────────────────────
echo "[ 1/5 ] Checking Python version..."
if ! command -v python3 &> /dev/null; then
    echo "  ERROR: python3 not found. Install from https://python.org"
    exit 1
fi
echo "  Found: $(python3 --version)"

# ── 2. Create virtual environment ────────────────────────────────────────────
echo ""
echo "[ 2/5 ] Creating virtual environment (.venv)..."
if [ -d ".venv" ]; then
    echo "  .venv already exists, skipping."
else
    python3 -m venv .venv
    echo "  Created .venv"
fi

# ── 3. Activate ──────────────────────────────────────────────────────────────
echo ""
echo "[ 3/5 ] Activating virtual environment..."
source .venv/bin/activate
echo "  Activated."

# ── 4. Install requirements ──────────────────────────────────────────────────
echo ""
echo "[ 4/5 ] Installing requirements..."
pip install --upgrade pip --quiet
pip install -r requirements.txt
if [ $? -ne 0 ]; then
    echo "  ERROR: pip install failed."
    exit 1
fi
echo "  All packages installed."

# ── 5. Generate secret keys ──────────────────────────────────────────────────
echo ""
echo "[ 5/5 ] Generating secret keys for .env ..."

FPE_KEY=$(python3 -c "import os; print(os.urandom(32).hex())")
HMAC_SALT=$(python3 -c "import os,base64; print(base64.b64encode(os.urandom(32)).decode())")

cat > .env <<EOF
# FinFlag Environment Variables
# Generated by setup_env.sh — DO NOT COMMIT THIS FILE TO GIT

FINFLAG_FPE_KEY=$FPE_KEY
FINFLAG_HMAC_SALT=$HMAC_SALT
REDIS_URL=redis://localhost:6379
EOF

echo "  .env file created."

echo ""
echo "================================================"
echo "  Setup complete! Next steps:"
echo ""
echo "  Run the full pipeline demo:"
echo "    python -m ml_model.pipeline"
echo ""
echo "  Run all tests:"
echo "    pytest tests/ -v"
echo ""
echo "  Start the API Gateway:"
echo "    uvicorn gateway.main:app --reload --port 8000"
echo "================================================"
echo ""
