# FinFlag · Environment Setup Script (Windows PowerShell)
# Run this ONCE from the project root:  .\setup_env.ps1
# ------------------------------------------------------------------

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  FinFlag · Environment Setup" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# ── 1. Check Python version ─────────────────────────────────────────────────
Write-Host "[ 1/5 ] Checking Python version..." -ForegroundColor Yellow
$pyVersion = python --version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ERROR: Python not found. Download from https://python.org" -ForegroundColor Red
    exit 1
}
Write-Host "  Found: $pyVersion" -ForegroundColor Green

# ── 2. Create virtual environment ────────────────────────────────────────────
Write-Host ""
Write-Host "[ 2/5 ] Creating virtual environment (.venv)..." -ForegroundColor Yellow
if (Test-Path ".venv") {
    Write-Host "  .venv already exists, skipping." -ForegroundColor Gray
} else {
    python -m venv .venv
    Write-Host "  Created .venv" -ForegroundColor Green
}

# ── 3. Activate virtual environment ─────────────────────────────────────────
Write-Host ""
Write-Host "[ 3/5 ] Activating virtual environment..." -ForegroundColor Yellow
& ".venv\Scripts\Activate.ps1"
Write-Host "  Activated." -ForegroundColor Green

# ── 4. Install requirements ──────────────────────────────────────────────────
Write-Host ""
Write-Host "[ 4/5 ] Installing requirements..." -ForegroundColor Yellow
pip install --upgrade pip --quiet
pip install -r requirements.txt
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ERROR: pip install failed. Check requirements.txt" -ForegroundColor Red
    exit 1
}
Write-Host "  All packages installed." -ForegroundColor Green

# ── 5. Generate secret keys ──────────────────────────────────────────────────
Write-Host ""
Write-Host "[ 5/5 ] Generating secret keys for .env ..." -ForegroundColor Yellow

$fpeKey  = python -c "import os; print(os.urandom(32).hex())"
$hmacSalt = python -c "import os,base64; print(base64.b64encode(os.urandom(32)).decode())"

$envContent = @"
# FinFlag Environment Variables
# Generated by setup_env.ps1 — DO NOT COMMIT THIS FILE TO GIT

# AES-256 key for Format-Preserving Encryption (hex, 64 chars)
FINFLAG_FPE_KEY=$fpeKey

# Salt for HMAC identity hashing (base64)
FINFLAG_HMAC_SALT=$hmacSalt

# Redis connection URL (update if Redis is on a different host)
REDIS_URL=redis://localhost:6379
"@

$envContent | Out-File -FilePath ".env" -Encoding utf8
Write-Host "  .env file created with fresh secret keys." -ForegroundColor Green

# ── Summary ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  Setup complete! Next steps:" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Run the full pipeline demo:" -ForegroundColor White
Write-Host "    python -m ml_model.pipeline" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Run the FPE self-test:" -ForegroundColor White
Write-Host "    python gateway/fpe.py" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Run all tests:" -ForegroundColor White
Write-Host "    pytest tests/ -v" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Start the API Gateway:" -ForegroundColor White
Write-Host "    uvicorn gateway.main:app --reload --port 8000" -ForegroundColor Yellow
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""
